version: "3.7"

services:
  laravel:
    image: daxter1987/laravel
    container_name: CONTAINER_NAME
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
